@startuml
participant Actor
Actor -> Controller : chooseColor
activate Controller
Controller -> Game : availableColors
activate Game
Game --> Controller
deactivate Game
Controller -> Game : tryToAddPlayer
activate Game
create Player
Game -> Player : new
activate Player
Player --> Game
deactivate Player
Game --> Controller
deactivate Game
return
@enduml