# Controller.play()

@startuml
participant Actor
Actor -> Controller : play
activate Controller
loop gameIsFinished == false
alt refreshDisplay
Controller -> Controller : printGame
activate Controller
Controller --> Controller
deactivate Controller
end
Controller -> Command : getCommand
activate Command
Command -> Command : parse
activate Command
Command -> Command : matchCommandName
activate Command
Command --> Command
deactivate Command
Command --> Command
deactivate Command
Command --> Controller : command
deactivate Command
Controller -> Command : execute
activate Command
Command --> Controller : refreshDisplay
deactivate Command
Controller -> Replay : addState
activate Replay
Replay -> State : new
activate State
State --> Replay
deactivate State
Replay --> Controller
deactivate Replay
Controller -> Game : isFinished
activate Game
Game --> Controller : gameIsFinished
deactivate Game
end
alt refreshDisplay
Controller -> Controller : printGame
activate Controller
Controller --> Controller
deactivate Controller
end
Controller -> Game : exited
activate Game
Game --> Controller : exited
deactivate Game
alt exited
Controller -> GamePrinter : showRanking
activate GamePrinter
GamePrinter --> Controller
deactivate GamePrinter
end
Controller -> Controller : askSaveReplay
activate Controller
Controller --> Controller : saveReplay
deactivate Controller
alt saveReplay
Controller -> SaveLoadManager : saveReplay
activate SaveLoadManager
SaveLoadManager -> SaveLoadManager : saveReplay
activate SaveLoadManager
SaveLoadManager -> Reportable : report
activate Reportable
Reportable --> SaveLoadManager
deactivate Reportable
SaveLoadManager --> SaveLoadManager
deactivate SaveLoadManager
SaveLoadManager --> Controller
deactivate SaveLoadManager
end
return
@enduml