# HelpCommand

@startuml
participant Actor
Actor -> HelpCommand : execute
activate HelpCommand
HelpCommand -> Command : infoForHelp
activate Command
Command --> HelpCommand
deactivate Command
return
@enduml