@startuml
participant Actor
Actor -> Controller : run
activate Controller
Controller -> SaveLoadManager : loadReplay
activate SaveLoadManager
SaveLoadManager --> Controller
deactivate SaveLoadManager
Controller -> Replay : startReplay
activate Replay
Replay -> Replay : execute
activate Replay
Replay --> Replay
deactivate Replay
return
@enduml