@startuml
participant Actor
Actor -> Controller : run
activate Controller
Controller -> SaveLoadManager : loadGame
activate SaveLoadManager
SaveLoadManager --> Controller
deactivate SaveLoadManager
return
@enduml
